# Generated by Django 6.0.7 on 2026-08-01 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Kapitel raqami')),
                ('title', models.CharField(max_length=200, verbose_name='Dars mavzusi')),
                ('level', models.CharField(default='A1.1', max_length=10, verbose_name='Darajasi')),
                ('grammar_content', models.TextField(help_text='Kursbuch dars nazariyasi (HTML formatida)')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name="O'quvchi javobi")),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi")),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Baho (1-10)')),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmadi'), ('graded', 'Tekshirildi')], default='pending', max_length=10, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqti')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter', verbose_name='Qaysi Kapitel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
        ),
    ]
